[project]
name = "ktorgen-documentation"
version = "0.1.0"
description = "Only docs for KtorGen"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-shadcn>=0.9.7",
    "pygments>=2.19.2",
    "pymdown-extensions>=10.16.1",
]
