# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# https://developer.android.com/build/releases/gradle-plugin
agp = "9.0.1"

# https://developer.android.com/tools/releases/platforms
android-compileSdk = "36"
android-minSdk = "21"

# https://mvnrepository.com/artifact/androidx.room/room-compiler-processing-testing
androidx-room-compiler-testing = "2.8.4"

# https://github.com/Kotlin/dokka/releases
dokka = "2.1.0"

# https://github.com/JetBrains/gradle-changelog-plugin/releases
jetbrains-changelog = "2.5.0"

# https://github.com/JetBrains/java-annotations/releases
jetbrains-jvm-annotations = "26.0.2"

# https://github.com/google/truth/releases
google-truth = "1.4.5"

# https://github.com/JetBrains/kotlin/releases
# match according to androidx https://github.com/androidx/androidx/blob/androidx-main/gradle/libs.versions.toml#L55
kotlin = "2.2.20"

# https://github.com/square/kotlinpoet/releases
kotlin-poet = "2.2.0"

# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.6"

# https://github.com/google/ksp/releases
ksp-api = "2.2.20-2.0.4"
ksp-plugin = "2.3.5"

# https://github.com/pinterest/ktlint/releases
ktlint-pinterest = "1.7.1"

# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "14.0.1"

# https://github.com/ktorio/ktor/releases
ktor = "3.3.1" # don't update until kotlin 2.2.21 because wasm needs matchs stdlib version

ktorgen-version = "0.6.1-SNAPSHOT"

# https://github.com/SonarSource/sonar-scanner-gradle/releases
sonarqube = "7.2.2.6593"

# https://github.com/vanniktech/gradle-maven-publish-plugin/releases
maven-publish = "0.36.0"

[libraries]
# annotation
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-jvm-annotations" }
# compiler
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp-api" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-poet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlin-poet" }
ktor-http = { group = "io.ktor", name = "ktor-http", version = "3.2.0" }
# test compiler
androidx-room-compiler-testing = { group = "androidx.room", name = "room-compiler-processing-testing", version.ref = "androidx-room-compiler-testing" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "google-truth" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# samples
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorgen-annotations = { group = "io.github.kingg22", name = "ktorgen-annotations", version.ref = "ktorgen-version" }
ktorgen-compiler = { group = "io.github.kingg22", name = "ktorgen-compiler", version.ref = "ktorgen-version" }

# Libraries can be bundled together for easier import
[bundles]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
changelog = { id = "org.jetbrains.changelog", version.ref = "jetbrains-changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
