# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# https://developer.android.com/build/releases/gradle-plugin
agp = "8.11.1"

# https://developer.android.com/tools/releases/platforms
android-compileSdk = "36"
android-minSdk = "21"

# https://github.com/Kotlin/dokka/releases
dokka = "2.0.0"
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.2.0"
# https://github.com/square/kotlinpoet/releases
kotlin-poet = "2.2.0"
# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.1"
# https://github.com/google/ksp/releases
ksp = "2.2.0-2.0.2"
# https://github.com/pinterest/ktlint/releases
ktlint-pinterest = "1.6.0"
# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "13.0.0"
ktorgen-version = "0.1.0"
# https://github.com/vanniktech/gradle-maven-publish-plugin/releases
maven-publish = "0.34.0"

[libraries]
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlin-poet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlin-poet" }

# Libraries can be bundled together for easier import
[bundles]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
