name: Preview documentation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'annotations/**'
      - 'README.md'

concurrency: preview-${{ github.ref }}

jobs:
  preview_docs:
    if: github.event.pull_request.head.repo.full_name == github.repository && false
    permissions:
      contents: write
      pull-requests: write
      pages: write
    runs-on: ubuntu-latest
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true # needed for mkdocs include files
          persist-credentials: false

      - name: Cache konan
        uses: actions/cache@v5
        with:
          path: |
            ~/.konan/dependencies
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'jetbrains'
          cache: 'gradle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
          cache-read-only: true
          validate-wrappers: false

      - name: Build documentation with dokka
        run: ./gradlew annotations:dokkaGenerate --no-daemon

      - name: Setup uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1

      - name: Install dependencies
        run: uv sync --locked

      - name: Build documentation
        run: uv run mkdocs build

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@8ff09e486b4c23709012eedd3b42e9f0b95dd0c5 # v1.6.3
        with:
          source-dir: build/mkdocs
